@startuml

start

: число <
: граница = КВАДРАТНЫЙ КОРЕНЬ ИЗ число ]
: счётчик ПРИСВОИТЬ 2 ]

while (счётчик МЕНЬШЕ ИЛИ РАВНО граница) is (да)
    if (число ДЕЛИТЬСЯ НА счётчик БЕЗ ОСТАТКА) then (да)
        : ЛОЖЬ >
        end
    endif

    : счётчик ПРИБАВИТЬ 1;
endwhile (нет)

: ИСТИНА >

end

@enduml