@startuml

start

: результат = 0 ]
: счётчик = 1 ]

while (счётчик <= 10) is (да)
    : результат = результат + счётчик_чисел;
    : счётчик = счётчик + 1;
endwhile (нет)

: результат >

end

@enduml